language: php

php:
  - 7.3

sudo: false

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update && composer --version
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install --prefer-dist --no-interaction

before_script:
  - "php -S 127.0.0.1:19911 -t ./public &"
  - sleep 3

script:
  - vendor/bin/codecept run
