#!/usr/bin/env php
<?php

error_reporting(-1);

ini_set('display_errors', 'On');

$app = require_once __DIR__ . '/../bootstrap.php';

defined('VILOVEUL_WORKDIR') or define('VILOVEUL_WORKDIR', getcwd());

if (!is_dir(VILOVEUL_WORKDIR)) {
    throw new ErrorException("Workdir does not exists.");
}
if (!is_readable(VILOVEUL_WORKDIR)) {
    throw new ErrorException("Workdir is not readable.");
}

$status = $app->console()->run();

$app->terminate($status);
